import Image from "next/image";

/**
 * A real screenshot of the product, in the visitor's own theme.
 *
 * The site had no imagery at all: the "screenshot" on the features page was a
 * CSS-drawn browser frame with three grey dots and invented label/value rows,
 * which is the least persuasive thing you can put in front of somebody who has
 * never heard of the product.
 *
 * These are generated by `scripts/shot-marketing.mjs` from the seeded demo
 * workspace. Re-running it after a UI change refreshes the site, which is the
 * answer to the reason screenshots were rejected the first time.
 *
 * BOTH THEMES SHIP AND CSS PICKS. A visitor in dark mode looking at a picture
 * of a white app is being shown a different product from the one they would
 * get. `data-theme` is set by the pre-paint script in the document head, so
 * the right image is correct on the first frame with no flash and no
 * JavaScript. Both are fetched, which is the honest cost of the approach: two
 * images at this size are cheaper than the wrong one.
 */
export function ProductShot({
  name,
  alt,
  priority = false,
}: {
  /** Base filename in `public/shots`, without the theme suffix. */
  name: "tasks" | "content";
  /** What the screen shows. Never "a screenshot of the app". */
  alt: string;
  priority?: boolean;
}) {
  // Matches WIDTH/HEIGHT in scripts/shot-marketing.mjs. Explicit, so the space
  // is reserved before the image lands and nothing on the page jumps.
  const width = 1440;
  const height = 500;

  return (
    <div className="overflow-hidden rounded-shell border border-rule bg-sheet">
      <Image
        src={`/shots/${name}-light.png`}
        alt={alt}
        width={width}
        height={height}
        priority={priority}
        className="block h-auto w-full dark-hide"
      />
      <Image
        src={`/shots/${name}-dark.png`}
        alt={alt}
        width={width}
        height={height}
        priority={priority}
        className="light-hide block h-auto w-full"
      />
    </div>
  );
}
