-- PLS-111, follow-up. The activity stream had no total order.
--
-- Found by exercising the chain against the live database inside a rolled back
-- transaction, which is the only way it could have been found: it typechecks,
-- it lints, and it renders.
--
-- `create_task` writes two entries, "Created this" and, through
-- replace_task_assignees, "Assigned to X". Both are one transaction, `now()` is
-- the transaction start time, so both rows carry an IDENTICAL created_at.
-- `order by created_at` is then a tie, and Postgres resolves a tie by heap
-- order: the assignment rendered above the creation, and the order was not even
-- stable between two reads of the same task.
--
-- This is the same defect PLS-99 fixed on the BD transcript, where every answer
-- rendered above the question that produced it, and the same class as the
-- jobs[0] bug. A timestamp is not an ordering. Three of these now; the lesson
-- is that any table written more than once per transaction needs a sequence,
-- not a clock.

-- 1. A real order --------------------------------------------------------------
--
-- Insertion order is the true order of events, and a sequence is the only thing
-- that records it. created_at stays, because the stream still prints a date;
-- it just stops being what the rows are sorted by.

alter table task_comments
  add column seq bigint generated by default as identity;

drop index if exists task_comments_stream_idx;
create index task_comments_stream_idx on task_comments (task_id, seq);

-- 2. And the entries go in the order they happened -------------------------------
--
-- The sequence alone would have fixed the instability, but it would have frozen
-- the wrong order: replace_task_assignees ran first, so "Assigned to" would
-- have taken the lower number. The opening line of a task's record is that it
-- was created, so that write moves ahead of the assignment.

create or replace function create_task(
  target_org uuid,
  task_title text,
  task_detail text default '',
  task_due timestamptz default now(),
  linked_candidate uuid default null,
  task_origin text default 'manual',
  task_priority_in task_priority default 'normal',
  assignee_ids uuid[] default null,
  linked_company uuid default null
)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  new_id uuid;
  link   text := '';
  who    uuid;
begin
  if not is_org_member(target_org) then raise exception 'forbidden'; end if;
  if task_title is null or length(trim(task_title)) = 0 then
    raise exception 'a task needs a title';
  end if;
  if task_origin not in ('manual', 'claude') then raise exception 'unknown task origin'; end if;

  -- A link to somebody else's candidate or client would be a cross-tenant read
  -- dressed up as a foreign key, so both are checked against this org.
  if linked_candidate is not null and not exists (
    select 1 from candidates c where c.id = linked_candidate and c.org_id = target_org
  ) then
    raise exception 'that candidate is not in this workspace';
  end if;

  if linked_company is not null and not exists (
    select 1 from companies c where c.id = linked_company and c.org_id = target_org
  ) then
    raise exception 'that company is not in this workspace';
  end if;

  insert into tasks (org_id, ref, title, detail, due, origin, candidate_id,
                     company_id, priority)
  values (target_org, next_ref(target_org, 'TASK'), trim(task_title),
          coalesce(task_detail, ''), task_due, task_origin, linked_candidate,
          linked_company, task_priority_in)
  returning id into new_id;

  -- The opening entry names what it was linked to, because "Created this" on
  -- its own is the one line in the stream that tells you nothing.
  select coalesce(
           (select ' and linked it to ' || c.name from candidates c where c.id = linked_candidate),
           (select ' and linked it to ' || c.name from companies  c where c.id = linked_company),
           ''
         ) into link;

  -- A task Claude filed has no human behind its first entry, and the null
  -- author is what the stream reads as Claude.
  who := case when task_origin = 'claude' then null else auth.uid() end;
  perform append_task_event(new_id, 'Created this' || link || '.', who);

  -- After the opening line, never before it: this writes an entry of its own.
  if assignee_ids is not null and array_length(assignee_ids, 1) >= 1 then
    perform replace_task_assignees(new_id, assignee_ids);
  end if;

  return new_id;
end;
$$;

revoke execute on function create_task(uuid, text, text, timestamptz, uuid, text, task_priority, uuid[], uuid)
  from public, anon;
grant execute on function create_task(uuid, text, text, timestamptz, uuid, text, task_priority, uuid[], uuid)
  to authenticated, service_role;
